import { Node, Edge } from "@xyflow/react";

export const initialNodes: Node[] = [
  // SWIMLANES
  {
    id: "lane-customer",
    type: "swimlane",
    position: { x: 0, y: -50 },
    data: { label: "👤 Хэрэглэгч" },
    draggable: false,
    selectable: false,
    zIndex: -1,
  },
  {
    id: "lane-manager",
    type: "swimlane",
    position: { x: 400, y: -50 },
    data: { label: "👨💼 Менежер" },
    draggable: false,
    selectable: false,
    zIndex: -1,
  },
  {
    id: "lane-staff",
    type: "swimlane",
    position: { x: 800, y: -50 },
    data: { label: "🛠 Ажилчин" },
    draggable: false,
    selectable: false,
    zIndex: -1,
  },

  // NODES
  {
    id: "1",
    type: "step",
    position: { x: 100, y: 50 },
    data: {
      label: "Хэрэглэгч захиалга өгөх\n(утас / чатбот)",
      role: "👤 Хэрэглэгч",
    },
  },
  {
    id: "limit-check",
    type: "decision",
    position: { x: 500, y: 150 },
    data: { label: "Өдрийн захиалгын\nхязгаар шалгах" },
  },
  {
    id: "limit-reject",
    type: "step",
    position: { x: 100, y: 180 },
    data: {
      label: "Татгалзах эсвэл\nдараа өдөр рүү шилжүүлэх",
      status: "pending",
    },
  },
  {
    id: "2",
    type: "step",
    position: { x: 500, y: 320 },
    data: { label: "Менежер захиалгыг\nсистемд бүртгэх", role: "👨💼 Менежер" },
  },
  {
    id: "3",
    type: "decision",
    position: { x: 500, y: 460 },
    data: { label: "Хэмжээ авах\nшаардлагатай юу?" },
  },
  {
    id: "3a",
    type: "step",
    position: { x: 900, y: 490 },
    data: {
      label: "Газар дээр нь хэмжилт\nхийхээр төлөвлөх",
      role: "🛠 Ажилчин",
      status: "in-progress",
    },
  },
  {
    id: "4",
    type: "step",
    position: { x: 500, y: 640 },
    data: {
      label:
        "Хаалганы үзүүлэлтээ сонгох:\nХэмжээ, Загвар, Материал,\nЦоож, Суурилуулалт, Хүргэлт,\nНийт үнийн тооцоолол",
      role: "👨💼 Менежер",
    },
    style: { width: 240, height: 110 },
  },
  {
    id: "5",
    type: "step",
    position: { x: 500, y: 800 },
    data: {
      label: "Төлбөрийн мэдээллийг\nхэрэглэгч рүү илгээх",
      role: "👨💼 Менежер",
    },
  },
  {
    id: "6",
    type: "step",
    position: { x: 100, y: 800 },
    data: {
      label: "50% урьдчилгаа\nтөлбөр хүлээх",
      role: "👤 Хэрэглэгч",
      status: "pending",
    },
  },
  {
    id: "7",
    type: "decision",
    position: { x: 500, y: 950 },
    data: { label: "Төлбөр\nхүлээж авсан уу?" },
  },
  {
    id: "7a",
    type: "step",
    position: { x: 740, y: 980 },
    data: {
      label: "Хүлээгдэж буй төлөв",
      role: "👨💼 Менежер",
      status: "pending",
    },
  },
  {
    id: "8",
    type: "step",
    position: { x: 500, y: 1140 },
    data: {
      label: "Захиалга баталгаажуулж\nҮйлдвэрлэл эхлүүлэх",
      role: "👨💼 Менежер",
      status: "in-progress",
    },
  },
  {
    id: "9_1",
    type: "step",
    position: { x: 900, y: 1280 },
    data: { label: "Зүсвэр", status: "in-progress", role: "🛠 Ажилчин" },
  },
  {
    id: "9_2",
    type: "step",
    position: { x: 900, y: 1400 },
    data: { label: "Угсралт", status: "in-progress", role: "🛠 Ажилчин" },
  },
  {
    id: "9_3",
    type: "step",
    position: { x: 900, y: 1520 },
    data: { label: "Будаг", status: "in-progress", role: "🛠 Ажилчин" },
  },
  {
    id: "9_4",
    type: "step",
    position: { x: 900, y: 1640 },
    data: { label: "Өнгөлгөө", status: "in-progress", role: "🛠 Ажилчин" },
  },
  {
    id: "9_5",
    type: "step",
    position: { x: 900, y: 1760 },
    data: { label: "Бэлэн болсон", status: "completed", role: "🛠 Ажилчин" },
  },
  {
    id: "10",
    type: "step",
    position: { x: 500, y: 1880 },
    data: {
      label: "Захиалга бэлэн болсныг\nхэрэглэгчид мэдэгдэх",
      role: "👨💼 Менежер",
      status: "completed",
    },
  },
  {
    id: "10a",
    type: "step",
    position: { x: 100, y: 1880 },
    data: {
      label: "Хэрэглэгч мэдэгдэл\nхүлээн авах",
      role: "👤 Хэрэглэгч",
      status: "completed",
    },
  },
];

export const initialEdges: Edge[] = [
  {
    id: "e1-limit",
    source: "1",
    target: "limit-check",
    sourceHandle: "s-right",
    targetHandle: "t-top",
    type: "smoothstep",
  },
  {
    id: "elimit-reject",
    source: "limit-check",
    target: "limit-reject",
    sourceHandle: "s-left",
    targetHandle: "t-right",
    type: "smoothstep",
    label: ">= хязгаар",
  },
  {
    id: "elimit-2",
    source: "limit-check",
    target: "2",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
    label: "< хязгаар",
  },
  {
    id: "e2-3",
    source: "2",
    target: "3",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
  },
  {
    id: "e3-3a",
    source: "3",
    target: "3a",
    sourceHandle: "s-right",
    targetHandle: "t-left",
    type: "smoothstep",
    label: "Тийм",
  },
  {
    id: "e3-4",
    source: "3",
    target: "4",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
    label: "Үгүй",
  },
  {
    id: "e3a-4",
    source: "3a",
    target: "4",
    sourceHandle: "s-bottom",
    targetHandle: "t-right",
    type: "smoothstep",
  },
  {
    id: "e4-5",
    source: "4",
    target: "5",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
  },
  {
    id: "e5-6",
    source: "5",
    target: "6",
    sourceHandle: "s-left",
    targetHandle: "t-right",
    type: "smoothstep",
  },
  {
    id: "e6-7",
    source: "6",
    target: "7",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
  },
  {
    id: "e7-7a",
    source: "7",
    target: "7a",
    sourceHandle: "s-right",
    targetHandle: "t-left",
    type: "smoothstep",
    label: "Үгүй",
  },
  {
    id: "e7-8",
    source: "7",
    target: "8",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
    label: "Тийм",
  },
  {
    id: "e8-9_1",
    source: "8",
    target: "9_1",
    sourceHandle: "s-right",
    targetHandle: "t-left",
    type: "smoothstep",
  },
  {
    id: "e9_1-9_2",
    source: "9_1",
    target: "9_2",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
  },
  {
    id: "e9_2-9_3",
    source: "9_2",
    target: "9_3",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
  },
  {
    id: "e9_3-9_4",
    source: "9_3",
    target: "9_4",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
  },
  {
    id: "e9_4-9_5",
    source: "9_4",
    target: "9_5",
    sourceHandle: "s-bottom",
    targetHandle: "t-top",
    type: "smoothstep",
  },
  {
    id: "e9_5-10",
    source: "9_5",
    target: "10",
    sourceHandle: "s-bottom",
    targetHandle: "t-right",
    type: "smoothstep",
  },
  {
    id: "e10-10a",
    source: "10",
    target: "10a",
    sourceHandle: "s-left",
    targetHandle: "t-right",
    type: "smoothstep",
  },
].map((edge) => ({
  ...edge,
  animated: true,
  style: { stroke: "#64748b", strokeWidth: 2 },
  labelStyle: { fill: "#cbd5e1", fontWeight: 600, fontSize: 12 },
  labelBgStyle: { fill: "#1e293b", stroke: "#334155", strokeWidth: 1 },
  labelBgPadding: [8, 4],
  labelBgBorderRadius: 4,
}));
